Fix typo in error message

diff --git a/checkout-and-setup/action.yml b/checkout-and-setup/action.yml
--- a/checkout-and-setup/action.yml
+++ b/checkout-and-setup/action.yml
@@ -24,7 +24,7 @@ runs:
         shell: bash
         if: github.event_name == 'repository_dispatch' && github.event.client_payload.slash_command.args.named.sha == ''
         run: |
-          echo >&2 "Dispatched from a slash command but missing the `sha` argument"
+          echo >&2 "Dispatched from a slash command but missing the 'sha' argument"
           exit 1
       - name: Verify commit
         shell: bash
