Validate slash command arguments

diff --git a/checkout-and-setup/action.yml b/checkout-and-setup/action.yml
--- a/checkout-and-setup/action.yml
+++ b/checkout-and-setup/action.yml
@@ -18,14 +18,18 @@ runs:
           fetch-depth: 0
           ref: |
             ${{ github.event_name == 'repository_dispatch' &&
-                github.event.client_payload.slash_command.args.named.sha != '' &&
                 github.event.client_payload.pull_request.head.sha == github.event.client_payload.slash_command.args.named.sha &&
                 format('refs/pull/{0}/head', github.event.client_payload.pull_request.number) || '' }}
+      - name: Verify args
+        shell: bash
+        if: github.event_name == 'repository_dispatch' && github.event.client_payload.slash_command.args.named.sha == ''
+        run: |
+          echo >&2 "Dispatched from a slash command but missing the `sha` argument"
+          exit 1
       - name: Verify commit
         shell: bash
         run: |
           expected=${{ github.event_name == 'repository_dispatch' &&
-                github.event.client_payload.slash_command.args.named.sha != '' &&
                 github.event.client_payload.pull_request.head.sha || '' }}
           actual=$(git log -1 --format='%H')
           if [ -n "$expected" ] && [ "$actual" != "$expected" ]; then
